sudo: required
services:
 - docker
before_install:
 - docker build -t mrhaleemkhan/react-test -f ./client/Dockerfile.dev ./client
script:
 - docker run -e CI=true mrhaleemkhan/react-test npm test
after_success:
 - docker build -t mrhaleemkhan/multi-client ./client
 - docker build -t mrhaleemkhan/multi-nginx ./nginx
 - docker build -t mrhaleemkhan/multi-server ./server
 - docker build -t mrhaleemkhan/multi-worker ./worker
 # Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push it to docker hub
 - docker push muhammadhaleemswati/multi-client
 - docker push muhammadhaleemswati/multi-nginx
 - docker push muhammadhaleemswati/multi-server
 - docker push muhammadhaleemswati/multi-worker