sudo: required
services:
 - docker
before_install:
 - docker build -t muhammadhaleemswati/react-test -f ./client/Dockerfile.dev ./client
script:
 - docker run -e CI=true muhammadhaleemswati/react-test npm test
after_success:
 - docker build -t muhammadhaleemswati/multi-client ./client
 - docker build -t muhammadhaleemswati/multi-nginx ./nginx
 - docker build -t muhammadhaleemswati/multi-server ./server
 - docker build -t muhammadhaleemswati/multi-worker ./worker
 # Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push it to docker hub
 - docker push muhammadhaleemswati/multi-client
 - docker push muhammadhaleemswati/multi-nginx
 - docker push muhammadhaleemswati/multi-server
 - docker push muhammadhaleemswati/multi-worker
deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-us-east-2-302547432569"
 bucket_path: "multi-docker"
 on:
   branch: master
 access_key_id:
   secure: $AWS_ACCESS_KEY
 secret_access_key:
   secure: "$AWS_SECRET_KEY"